move *.mod.zip mod/
move *.it.zip it/
move *.xm.zip xm/
move *.s3m.zip s3m/
move *.669.zip 669/
move *.stm.zip stm/
move *.mtm.zip mtm/
move *.med.zip med/
move *.ahx.zip ahx/
move *.hvl.zip hvl/
